# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=256, verbose_name='Описание')),
                ('desc_image', models.FileField(upload_to='static/images/upload_imgs', verbose_name='Картинка к статье')),
                ('content', models.TextField(verbose_name='Основной текст')),
                ('public_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('file', models.FileField(upload_to='static/images/upload_imgs')),
                ('desc', models.TextField(max_length=256, verbose_name='Описание на странице')),
                ('service_name', models.CharField(default='description', max_length=24, unique=True, verbose_name='Служебное имя')),
            ],
            options={
                'verbose_name_plural': '0. Список описаний страниц',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('desc', models.TextField(max_length=256, verbose_name='Описание на странице')),
                ('service_name', models.CharField(default='gallery', max_length=24, unique=True, verbose_name='Служебное имя')),
            ],
        ),
        migrations.CreateModel(
            name='Graduations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('price', models.IntegerField(default=1500, verbose_name='Стоимость')),
                ('desc', models.TextField(max_length=256, verbose_name='Кракое описание')),
                ('service_name', models.CharField(default='graduations_name', max_length=24, unique=True, verbose_name='Служебное имя')),
            ],
            options={
                'verbose_name_plural': '1.3 Выпускные съёмки',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=256, verbose_name='Кракое описание')),
                ('service_name', models.CharField(default='product', max_length=24, unique=True, verbose_name='Служебное имя')),
                ('hall_size', models.IntegerField(default=50, verbose_name='Размер зала')),
                ('price', models.IntegerField(default=1500, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name_plural': '1.2 Залы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Masterclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('teacher', models.CharField(max_length=32, verbose_name='Преподаватель')),
                ('price', models.IntegerField(default=1500, verbose_name='Стоимость')),
                ('num_of_place', models.IntegerField(default=10, verbose_name='Количество мест')),
                ('short_desc', models.TextField(max_length=256, verbose_name='Кракое описание мастер-класса')),
                ('full_desc', models.TextField(max_length=512, verbose_name='Полное описание мастер-класса')),
                ('desc_image', models.FileField(upload_to='static/images/upload_imgs', verbose_name='Титульное изображение')),
            ],
            options={
                'verbose_name_plural': '2.2 Мастерклассы',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название картинки')),
                ('file', models.FileField(upload_to='static/images/upload_imgs')),
                ('desc', models.TextField(blank=True, max_length=128, null=True, verbose_name='Описание изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=256, verbose_name='Кракое описание')),
                ('service_name', models.CharField(default='product', max_length=24, unique=True, verbose_name='Служебное имя')),
            ],
            options={
                'verbose_name_plural': '1.1 Съёмки',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsefulArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('desc', models.TextField(max_length=256, verbose_name='Описание статьи')),
                ('desc_image', models.FileField(upload_to='static/images/upload_imgs', verbose_name='Картинка к статье')),
                ('service_name', models.CharField(default='article', max_length=24, unique=True, verbose_name='Служебное имя')),
            ],
            options={
                'verbose_name_plural': '2.3 Статьи на странице "Полезное"',
            },
        ),
        migrations.CreateModel(
            name='PicGraduations',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Picture')),
                ('galleryGraduations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.Graduations')),
            ],
            options={
                'verbose_name_plural': 'Все изображения со страницы выпускных съёмок',
            },
            bases=('mainApp.picture',),
        ),
        migrations.CreateModel(
            name='PicHalls',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Picture')),
                ('galleryHalls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.Hall')),
            ],
            options={
                'verbose_name_plural': 'Все изображения залов',
            },
            bases=('mainApp.picture',),
        ),
        migrations.CreateModel(
            name='PicMasterclass',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Picture')),
                ('galleryMasterclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.Masterclass')),
            ],
            options={
                'verbose_name_plural': 'Все изображения со страницы мастерклассов',
            },
            bases=('mainApp.picture',),
        ),
        migrations.CreateModel(
            name='PicSession',
            fields=[
                ('picture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Picture')),
                ('gallerySession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.Session')),
            ],
            options={
                'verbose_name_plural': 'Все изображения съёмок',
            },
            bases=('mainApp.picture',),
        ),
    ]
