# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('desc', models.TextField(max_length=256, verbose_name='Описание на странице')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/images/school/', verbose_name='File')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название картинки')),
                ('image', models.FileField(upload_to='static/images/school')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': "Основные изображения на странице 'Фотошколы'",
            },
        ),
    ]
